- name: install all the packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - apt-transport-https
    - ca-certificates


- name: Disable swap
  shell: |
    swapoff -a
    sed -i '/ swap / s/^/#/' /etc/fstab

- name: Ensure sysctl settings for Kubernetes
  shell: |
    modprobe overlay
    modprobe br_netfilter
    echo "net.bridge.bridge-nf-call-iptables = 1" >> /etc/sysctl.conf
    echo "net.bridge.bridge-nf-call-ip6tables = 1" >> /etc/sysctl.conf
    echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
    sysctl --system
- name: Delete the Kubernetes GPG key file
  file:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    state: absent

- name: Download Kubernetes GPG key and save in dearmored format
  ansible.builtin.shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: add Kubernetes GPG key and save in dearmored format
  ansible.builtin.shell: |
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
- name: Set correct permissions for Kubernetes GPG key
  file:
    path: /etc/apt/sources.list.d/kubernetes.list
    mode: '0644'


- name: Set correct permissions for Kubernetes GPG key
  file:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    mode: '0644'
- name: update
  apt:
    update_cache: yes


- name: install all the packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - kubeadm
    - kubelet
    - kubectl
    - apt-transport-https
    - ca-certificates
    - curl
    - gpg
    - containerd


- name: start all the packages
  systemd:
    name: containerd
    state: started
    enabled: yes

    
- name: Hold kubeadm
  ansible.builtin.dpkg_selections:
    name: kubeadm
    selection: hold
- name: Ensure the directory exists for containerd config
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: get defualt containerd configuration
  shell: |
    touch /etc/containerd/config.toml
    sudo containerd config default > /etc/containerd/config.toml

    
- name: Update SystemdCgroup to true in containerd config
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^\s*SystemdCgroup\s*='
    line: '  SystemdCgroup = true'
    insertafter: '^\[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options\]'
    backup: yes